/**
 * The web demo registry: export name -> a live React demo.
 *
 * `webExports` is checked against `docs/components.md` at build time by
 * `registry-audit.ts`, so a component that ships without a demo fails the
 * typecheck instead of rendering a blank page. Compound families (Dialog,
 * Tabs, Field, …) expose a namespace object *and* its parts; the namespace
 * and every part resolve to the same family demo, because the part has no
 * meaning outside its parent.
 */
import { componentsOn } from "../../generated/manifest";
import {
  AvatarDemo,
  BadgeDemo,
  BannerDemo,
  BootIndicatorDemo,
  ButtonDemo,
  ButtonGroupDemo,
  CardDemo,
  ChipDemo,
  CircularProgressDemo,
  EmptyStateDemo,
  ExtendedFabDemo,
  FabDemo,
  FabMenuDemo,
  FilterChipRowDemo,
  IconButtonDemo,
  KbdDemo,
  KernErrorBoundaryDemo,
  LabelDemo,
  LinearProgressDemo,
  LinkDemo,
  ListItemDemo,
  LoaderDemo,
  LoadingButtonDemo,
  LoadingIndicatorDemo,
  LoadingRegionDemo,
  PageLoaderDemo,
  SeparatorDemo,
  SkeletonDemo,
  TextDemo,
} from "./display";
import {
  CheckboxDemo,
  CheckboxGroupDemo,
  FieldDemo,
  FieldMessageDemo,
  FieldsetDemo,
  FormDemo,
  InputDemo,
  InputOTPDemo,
  NumberFieldDemo,
  RadioGroupDemo,
  SearchDemo,
  SliderDemo,
  SwitchDemo,
  TextareaDemo,
  ToggleDemo,
  ToggleGroupDemo,
} from "./forms";
import {
  ActionSheetDemo,
  AppShellDemo,
  BottomSheetDemo,
  BottomSheetPickerDemo,
  CarouselDemo,
  CollapsibleDemo,
  CommandDemo,
  ContextMenuDemo,
  DialogDemo,
  DockSheetDemo,
  DrawerDemo,
  EntitySheetDemo,
  MenuDemo,
  MenuScreenDemo,
  MenuSheetDemo,
  MeterDemo,
  NavigationBarDemo,
  NavigationDrawerDemo,
  NavigationMenuDemo,
  PaginationDemo,
  PaneDemo,
  PopoverDemo,
  PreviewCardDemo,
  ProgressDemo,
  ScrollAreaDemo,
  SearchBarDemo,
  SecondaryTabsDemo,
  SegmentedButtonDemo,
  SelectDemo,
  SheetDemo,
  SheetSurfaceDemo,
  SidebarDemo,
  SnapSheetDemo,
  SplitButtonDemo,
  SplitDemo,
  TableDemo,
  TabsDemo,
  TimePickerDemo,
  ToolbarDemo,
  TooltipDemo,
  TopAppBarDemo,
  AccordionDemo as WebAccordionDemo,
} from "./layout";
import {
  AlertDialogDemo,
  AutocompleteDemo,
  CalendarDemo,
  ComboboxDemo,
  CountrySelectDemo,
  MenubarDemo,
  NativeSelectDemo,
  SnackbarDemo,
  SonnerDemo,
} from "./pickers";

export type WebDemo = () => React.ReactElement;

/**
 * Every exported symbol, mapped to the demo that renders it. A family
 * namespace and its parts share one demo; the page states that the part is
 * exercised inside its parent.
 */
const byExport: Record<string, WebDemo> = {
  Accordion: WebAccordionDemo,
  AlertDialog: AlertDialogDemo,
  AlertDialogClose: AlertDialogDemo,
  AlertDialogContent: AlertDialogDemo,
  AlertDialogDescription: AlertDialogDemo,
  AlertDialogRoot: AlertDialogDemo,
  AlertDialogTitle: AlertDialogDemo,
  AlertDialogTrigger: AlertDialogDemo,
  Autocomplete: AutocompleteDemo,
  AutocompleteContent: AutocompleteDemo,
  AutocompleteEmpty: AutocompleteDemo,
  AutocompleteInput: AutocompleteDemo,
  AutocompleteItem: AutocompleteDemo,
  AutocompleteLabel: AutocompleteDemo,
  AutocompleteRoot: AutocompleteDemo,
  Calendar: CalendarDemo,
  Combobox: ComboboxDemo,
  ComboboxClear: ComboboxDemo,
  ComboboxContent: ComboboxDemo,
  ComboboxEmpty: ComboboxDemo,
  ComboboxInput: ComboboxDemo,
  ComboboxItem: ComboboxDemo,
  ComboboxLabel: ComboboxDemo,
  ComboboxRoot: ComboboxDemo,
  ComboboxTrigger: ComboboxDemo,
  CountrySelect: CountrySelectDemo,
  CountrySelectContent: CountrySelectDemo,
  CountrySelectItem: CountrySelectDemo,
  CountrySelectLabel: CountrySelectDemo,
  CountrySelectRoot: CountrySelectDemo,
  CountrySelectTrigger: CountrySelectDemo,
  CountrySelectValue: CountrySelectDemo,
  Menubar: MenubarDemo,
  MenubarContent: MenubarDemo,
  MenubarItem: MenubarDemo,
  MenubarMenu: MenubarDemo,
  MenubarRoot: MenubarDemo,
  MenubarTrigger: MenubarDemo,
  NativeSelect: NativeSelectDemo,
  Snackbar: SnackbarDemo,
  SnackbarAction: SnackbarDemo,
  SnackbarClose: SnackbarDemo,
  SnackbarDescription: SnackbarDemo,
  SnackbarList: SnackbarDemo,
  SnackbarProvider: SnackbarDemo,
  SnackbarRoot: SnackbarDemo,
  SnackbarTitle: SnackbarDemo,
  SnackbarViewport: SnackbarDemo,
  Sonner: SonnerDemo,
  SonnerAction: SonnerDemo,
  SonnerClose: SonnerDemo,
  SonnerDescription: SonnerDemo,
  SonnerList: SonnerDemo,
  SonnerProvider: SonnerDemo,
  SonnerRoot: SonnerDemo,
  SonnerTitle: SonnerDemo,
  SonnerViewport: SonnerDemo,
  createSonnerManager: SonnerDemo,
  AccordionHeader: WebAccordionDemo,
  AccordionItem: WebAccordionDemo,
  AccordionPanel: WebAccordionDemo,
  AccordionRoot: WebAccordionDemo,
  AccordionTrigger: WebAccordionDemo,
  ActionSheet: ActionSheetDemo,
  AppShell: AppShellDemo,
  Avatar: AvatarDemo,
  AvatarFallback: AvatarDemo,
  AvatarImage: AvatarDemo,
  AvatarRoot: AvatarDemo,
  Badge: BadgeDemo,
  Banner: BannerDemo,
  BannerAction: BannerDemo,
  BootIndicator: BootIndicatorDemo,
  BottomSheet: BottomSheetDemo,
  BottomSheetPicker: BottomSheetPickerDemo,
  Button: ButtonDemo,
  ButtonGroup: ButtonGroupDemo,
  Card: CardDemo,
  Carousel: CarouselDemo,
  Checkbox: CheckboxDemo,
  CheckboxGroup: CheckboxGroupDemo,
  CheckboxGroupItem: CheckboxGroupDemo,
  CheckboxGroupRoot: CheckboxGroupDemo,
  Chip: ChipDemo,
  CircularProgress: CircularProgressDemo,
  Collapsible: CollapsibleDemo,
  CollapsiblePanel: CollapsibleDemo,
  CollapsibleRoot: CollapsibleDemo,
  CollapsibleTrigger: CollapsibleDemo,
  Command: CommandDemo,
  CommandContent: CommandDemo,
  CommandEmpty: CommandDemo,
  CommandGroupLabel: CommandDemo,
  CommandInput: CommandDemo,
  CommandItem: CommandDemo,
  CommandList: CommandDemo,
  CommandRoot: CommandDemo,
  CommandSeparator: CommandDemo,
  ContextMenu: ContextMenuDemo,
  ContextMenuContent: ContextMenuDemo,
  ContextMenuItem: ContextMenuDemo,
  ContextMenuRoot: ContextMenuDemo,
  ContextMenuSeparator: ContextMenuDemo,
  ContextMenuTrigger: ContextMenuDemo,
  Dialog: DialogDemo,
  DialogClose: DialogDemo,
  DialogContent: DialogDemo,
  DialogDescription: DialogDemo,
  DialogRoot: DialogDemo,
  DialogTitle: DialogDemo,
  DialogTrigger: DialogDemo,
  DockSheet: DockSheetDemo,
  Drawer: DrawerDemo,
  DrawerClose: DrawerDemo,
  DrawerContent: DrawerDemo,
  DrawerDescription: DrawerDemo,
  DrawerRoot: DrawerDemo,
  DrawerTitle: DrawerDemo,
  DrawerTrigger: DrawerDemo,
  EmptyState: EmptyStateDemo,
  EntitySheet: EntitySheetDemo,
  ExtendedFab: ExtendedFabDemo,
  Fab: FabDemo,
  FabMenu: FabMenuDemo,
  Field: FieldDemo,
  FieldDescription: FieldDemo,
  FieldError: FieldDemo,
  FieldLabel: FieldDemo,
  FieldMessage: FieldMessageDemo,
  FieldRoot: FieldDemo,
  Fieldset: FieldsetDemo,
  FieldsetLegend: FieldsetDemo,
  FieldsetRoot: FieldsetDemo,
  FilterChipRow: FilterChipRowDemo,
  Form: FormDemo,
  IconButton: IconButtonDemo,
  Input: InputDemo,
  InputOTP: InputOTPDemo,
  InputOTPInput: InputOTPDemo,
  InputOTPRoot: InputOTPDemo,
  Kbd: KbdDemo,
  KernErrorBoundary: KernErrorBoundaryDemo,
  Label: LabelDemo,
  LinearProgress: LinearProgressDemo,
  Link: LinkDemo,
  LinkButton: LinkDemo,
  LinkProvider: LinkDemo,
  ListItem: ListItemDemo,
  Loader: LoaderDemo,
  PageLoader: PageLoaderDemo,
  LoadingButton: LoadingButtonDemo,
  LoadingIndicator: LoadingIndicatorDemo,
  LoadingRegion: LoadingRegionDemo,
  Menu: MenuDemo,
  MenuContent: MenuDemo,
  MenuGroupLabel: MenuDemo,
  MenuItem: MenuDemo,
  MenuRoot: MenuDemo,
  MenuSeparator: MenuDemo,
  MenuTrigger: MenuDemo,
  MenuScreen: MenuScreenDemo,
  MenuSheet: MenuSheetDemo,
  Meter: MeterDemo,
  MeterLabel: MeterDemo,
  MeterRoot: MeterDemo,
  MeterValue: MeterDemo,
  NavigationMenu: NavigationMenuDemo,
  NavigationMenuContent: NavigationMenuDemo,
  NavigationMenuItem: NavigationMenuDemo,
  NavigationMenuLink: NavigationMenuDemo,
  NavigationMenuList: NavigationMenuDemo,
  NavigationMenuRoot: NavigationMenuDemo,
  NavigationBar: NavigationBarDemo,
  NavigationBarItem: NavigationBarDemo,
  NavigationDrawer: NavigationDrawerDemo,
  NavigationMenuTrigger: NavigationMenuDemo,
  NumberField: NumberFieldDemo,
  NumberFieldInput: NumberFieldDemo,
  NumberFieldRoot: NumberFieldDemo,
  Pagination: PaginationDemo,
  Pane: PaneDemo,
  Popover: PopoverDemo,
  PopoverClose: PopoverDemo,
  PopoverContent: PopoverDemo,
  PopoverDescription: PopoverDemo,
  PopoverRoot: PopoverDemo,
  PopoverTitle: PopoverDemo,
  PopoverTrigger: PopoverDemo,
  PreviewCard: PreviewCardDemo,
  PreviewCardContent: PreviewCardDemo,
  PreviewCardRoot: PreviewCardDemo,
  PreviewCardTrigger: PreviewCardDemo,
  Progress: ProgressDemo,
  ProgressLabel: ProgressDemo,
  ProgressRoot: ProgressDemo,
  ProgressValue: ProgressDemo,
  RadioGroup: RadioGroupDemo,
  RadioGroupItem: RadioGroupDemo,
  ScrollArea: ScrollAreaDemo,
  ScrollAreaRoot: ScrollAreaDemo,
  ScrollAreaScrollbar: ScrollAreaDemo,
  ScrollAreaViewport: ScrollAreaDemo,
  Search: SearchDemo,
  SearchBar: SearchBarDemo,
  SecondaryTabs: SecondaryTabsDemo,
  SegmentedButton: SegmentedButtonDemo,
  SegmentedButtonItem: SegmentedButtonDemo,
  SegmentedButtonRoot: SegmentedButtonDemo,
  Select: SelectDemo,
  SelectContent: SelectDemo,
  SelectGroupLabel: SelectDemo,
  SelectItem: SelectDemo,
  SelectItemText: SelectDemo,
  SelectRoot: SelectDemo,
  SelectSeparator: SelectDemo,
  SelectTrigger: SelectDemo,
  SelectValue: SelectDemo,
  Separator: SeparatorDemo,
  Sheet: SheetDemo,
  SheetClose: SheetDemo,
  SheetContent: SheetDemo,
  SheetDescription: SheetDemo,
  SheetRoot: SheetDemo,
  SheetTitle: SheetDemo,
  SheetTrigger: SheetDemo,
  SheetSurface: SheetSurfaceDemo,
  Sidebar: SidebarDemo,
  SidebarContent: SidebarDemo,
  SidebarFooter: SidebarDemo,
  SidebarHeader: SidebarDemo,
  SidebarItem: SidebarDemo,
  SidebarProvider: SidebarDemo,
  Skeleton: SkeletonDemo,
  Slider: SliderDemo,
  SliderLabel: SliderDemo,
  SliderRoot: SliderDemo,
  SliderThumb: SliderDemo,
  SliderValue: SliderDemo,
  SnapSheet: SnapSheetDemo,
  Split: SplitDemo,
  SplitButton: SplitButtonDemo,
  SplitGrid: SplitDemo,
  SplitPanel: SplitDemo,
  Switch: SwitchDemo,
  Table: TableDemo,
  TableBody: TableDemo,
  TableCaption: TableDemo,
  TableCell: TableDemo,
  TableHead: TableDemo,
  TableHeader: TableDemo,
  TableRoot: TableDemo,
  TableRow: TableDemo,
  Tabs: TabsDemo,
  TabsList: TabsDemo,
  TabsPanel: TabsDemo,
  TabsRoot: TabsDemo,
  TabsTab: TabsDemo,
  TimePicker: TimePickerDemo,
  Text: TextDemo,
  Textarea: TextareaDemo,
  Toggle: ToggleDemo,
  ToggleGroup: ToggleGroupDemo,
  ToggleGroupItem: ToggleGroupDemo,
  ToggleGroupRoot: ToggleGroupDemo,
  Toolbar: ToolbarDemo,
  ToolbarButton: ToolbarDemo,
  ToolbarGroup: ToolbarDemo,
  ToolbarRoot: ToolbarDemo,
  ToolbarSeparator: ToolbarDemo,
  Tooltip: TooltipDemo,
  TooltipContent: TooltipDemo,
  TooltipProvider: TooltipDemo,
  TooltipRoot: TooltipDemo,
  TooltipTrigger: TooltipDemo,
  TopAppBar: TopAppBarDemo,
  TopAppBarToggle: TopAppBarDemo,
};

/** The demo for a manifest row, or undefined when the row has no live demo. */
export function demoFor(exportName: string): WebDemo | undefined {
  return byExport[exportName];
}

export const WEB_DEMOS = byExport;

/**
 * Web per-part no-preview reasons, keyed like the mobile map below — EMPTY
 * on purpose. Thirteen web families currently render mobile-frame reasons
 * on their gallery cards (measured: bottom-sheet*, dock/entity-sheet,
 * filter-chip-row, menu-screen/sheet, navigation-bar/drawer, pane,
 * secondary-tabs, snap-sheet, top-app-bar) because previewReason looked
 * everything up in the mobile map. Showing phone-frame text ("in a browser
 * frame", "RNW renderer") on a web card is a false claim about the web
 * component, so web lookups stop at this map: demo-less web families
 * honestly render "Demo coming" until a real web reason is authored here.
 */
export const WEB_PREVIEW_REASONS: Record<string, string> = {};

export const WEB_EXPORT_COUNT = componentsOn("web").length;

export const WEB_DEMO_COUNT = componentsOn("web").filter(
  (component) => byExport[component.export] !== undefined,
).length;

/** Manifest rows with no live demo, with the reason. Never silently empty. */
export function undemoedWebExports(): { export: string; slug: string }[] {
  return componentsOn("web")
    .filter((component) => byExport[component.export] === undefined)
    .map((component) => ({ export: component.export, slug: component.slug }));
}
