// AUTO-GENERATED by tools/generate.ts — shape registry.
// Do not edit by hand. Change the assets or config and re-run:
//   bun run generate

import type { IconWeight, IconWeightRegistry } from "../../../core/types";
import { shapes as w400 } from "./w400";

/** Shape data by Material Symbols weight axis value. */
export const ICON_SHAPES: IconWeightRegistry = {
  400: w400,
};

/** Weights that have local shape data. */
export const ICON_WEIGHTS = [400] as const satisfies readonly IconWeight[];
