// AUTO-GENERATED by tools/generate.ts — catalog manifest.
// Do not edit by hand. Change the assets or config and re-run:
//   bun run generate

import type { IconManifest } from "../../core/types";

/**
 * Provenance for the committed shape data. Deliberately free of timestamps so
 * regeneration is byte-identical and `tools/check.ts` can diff it.
 */
export const ICON_MANIFEST: IconManifest = {
  viewBox: "0 0 24 24",
  precision: 3,
  weights: [400],
  defaultWeight: 400,
  counts: {
    total: 1340,
    material: 1340,
    brand: 0,
    filledReusesOutline: 465,
  },
  source: {
    package: "@material-symbols/svg-400",
    version: "0.47.2",
    style: "rounded",
    weight: 400,
    opticalSize: 48,
    license: "Apache-2.0",
    licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0",
  },
};
