/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsGuidesRouteImport } from './routes/docs/guides'
import { Route as ThemeIndexRouteImport } from './routes/theme/index'
import { Route as ComponentsMobileIndexRouteImport } from './routes/components/mobile/index'
import { Route as ComponentsWebIndexRouteImport } from './routes/components/web/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGuidesRoute = DocsGuidesRouteImport.update({
  id: '/docs/guides',
  path: '/docs/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeIndexRoute = ThemeIndexRouteImport.update({
  id: '/theme/',
  path: '/theme/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsMobileIndexRoute = ComponentsMobileIndexRouteImport.update({
  id: '/components/mobile/',
  path: '/components/mobile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsWebIndexRoute = ComponentsWebIndexRouteImport.update({
  id: '/components/web/',
  path: '/components/web/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/getting-started': typeof GettingStartedRoute
  '/docs/guides': typeof DocsGuidesRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/theme/': typeof ThemeIndexRoute
  '/components/mobile/': typeof ComponentsMobileIndexRoute
  '/components/web/': typeof ComponentsWebIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/getting-started': typeof GettingStartedRoute
  '/docs/guides': typeof DocsGuidesRoute
  '/components': typeof ComponentsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/theme': typeof ThemeIndexRoute
  '/components/mobile': typeof ComponentsMobileIndexRoute
  '/components/web': typeof ComponentsWebIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/getting-started': typeof GettingStartedRoute
  '/docs/guides': typeof DocsGuidesRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/theme/': typeof ThemeIndexRoute
  '/components/mobile/': typeof ComponentsMobileIndexRoute
  '/components/web/': typeof ComponentsWebIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/getting-started'
    | '/docs/guides'
    | '/components/'
    | '/docs/'
    | '/theme/'
    | '/components/mobile/'
    | '/components/web/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/getting-started'
    | '/docs/guides'
    | '/components'
    | '/docs'
    | '/theme'
    | '/components/mobile'
    | '/components/web'
  id:
    | '__root__'
    | '/'
    | '/getting-started'
    | '/docs/guides'
    | '/components/'
    | '/docs/'
    | '/theme/'
    | '/components/mobile/'
    | '/components/web/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GettingStartedRoute: typeof GettingStartedRoute
  DocsGuidesRoute: typeof DocsGuidesRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ThemeIndexRoute: typeof ThemeIndexRoute
  ComponentsMobileIndexRoute: typeof ComponentsMobileIndexRoute
  ComponentsWebIndexRoute: typeof ComponentsWebIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/guides': {
      id: '/docs/guides'
      path: '/docs/guides'
      fullPath: '/docs/guides'
      preLoaderRoute: typeof DocsGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/': {
      id: '/theme/'
      path: '/theme'
      fullPath: '/theme/'
      preLoaderRoute: typeof ThemeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/mobile/': {
      id: '/components/mobile/'
      path: '/components/mobile'
      fullPath: '/components/mobile/'
      preLoaderRoute: typeof ComponentsMobileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/web/': {
      id: '/components/web/'
      path: '/components/web'
      fullPath: '/components/web/'
      preLoaderRoute: typeof ComponentsWebIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GettingStartedRoute: GettingStartedRoute,
  DocsGuidesRoute: DocsGuidesRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ThemeIndexRoute: ThemeIndexRoute,
  ComponentsMobileIndexRoute: ComponentsMobileIndexRoute,
  ComponentsWebIndexRoute: ComponentsWebIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
