// AUTO-GENERATED by tools/generate.ts — weight 400 registry.
// Do not edit by hand. Change the assets or config and re-run:
//   bun run generate

import type { IconShapeMap } from "../../../../core/types";
import { shapes as chunkA } from "./a";
import { shapes as chunkB } from "./b";
import { shapes as chunkC } from "./c";
import { shapes as chunkD } from "./d";
import { shapes as chunkE } from "./e";
import { shapes as chunkF } from "./f";
import { shapes as chunkG } from "./g";
import { shapes as chunkH } from "./h";
import { shapes as chunkI } from "./i";
import { shapes as chunkJ } from "./j";
import { shapes as chunkK } from "./k";
import { shapes as chunkL } from "./l";
import { shapes as chunkM } from "./m";
import { shapes as chunkN } from "./n";
import { shapes as chunkO } from "./o";
import { shapes as chunkP } from "./p";
import { shapes as chunkQ } from "./q";
import { shapes as chunkR } from "./r";
import { shapes as chunkS } from "./s";
import { shapes as chunkT } from "./t";
import { shapes as chunkU } from "./u";
import { shapes as chunkV } from "./v";
import { shapes as chunkW } from "./w";
import { shapes as chunkY } from "./y";
import { shapes as chunkZ } from "./z";

/**
 * Every shape for weight 400, keyed by icon name.
 *
 * Chunked by first character so a bundle that only ever renders icons from a
 * known slice can be code-split; a dynamic `<Icon name={…} />` pulls the
 * whole weight, which is why `config/kern-icon-set.txt` stays curated.
 */
export const shapes: IconShapeMap = {
  ...chunkA,
  ...chunkB,
  ...chunkC,
  ...chunkD,
  ...chunkE,
  ...chunkF,
  ...chunkG,
  ...chunkH,
  ...chunkI,
  ...chunkJ,
  ...chunkK,
  ...chunkL,
  ...chunkM,
  ...chunkN,
  ...chunkO,
  ...chunkP,
  ...chunkQ,
  ...chunkR,
  ...chunkS,
  ...chunkT,
  ...chunkU,
  ...chunkV,
  ...chunkW,
  ...chunkY,
  ...chunkZ,
};
