/**
 * Emits generated icon code from the normalized catalog.
 *
 * Output is deterministic — no timestamps, no host paths, sorted keys — so
 * `tools/check.ts` can regenerate it in memory and byte-compare it against what
 * is committed. Everything is written under `src/sets/`:
 *
 *   src/sets/material/          symbols, names, manifest
 *   src/sets/material/shapes/   per-weight shape registry chunks
 *   src/sets/                   extra set registry
 */

import type { Catalog, CatalogEntry } from "./catalog";
import type { SourceConfig } from "./config";
import { ICON_SPEC, readSourceConfig } from "./config";
import { CHUNK_IDS, compareIconNames, toChunkId, toObjectKey } from "./naming";

/** Biome's default line width. Emitted lines that fit stay flat. */
const LINE_WIDTH = 80;

const BANNER = (target: string) =>
  [
    `// AUTO-GENERATED by tools/generate.ts — ${target}.`,
    "// Do not edit by hand. Change the assets or config and re-run:",
    "//   bun run generate",
    "",
  ].join("\n");

const VIEW_BOX = `0 0 ${ICON_SPEC.viewBoxSize} ${ICON_SPEC.viewBoxSize}`;

/** JS string literal for path data. Double-quoted, matching the formatter. */
function literal(d: string): string {
  return `"${d.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** Whether a one-line form fits the formatter's line width. */
function fits(line: string): boolean {
  return line.length <= LINE_WIDTH;
}

/** `{ o: "…", f: "…", r: "evenodd" }` — flat object for one shape entry. */
function shapeFlat(entry: CatalogEntry): string {
  const parts = [`o: ${literal(entry.outline)}`];
  if (!entry.filledIsOutline) parts.push(`f: ${literal(entry.filled)}`);
  if (entry.fillRule) parts.push(`r: "evenodd"`);
  return `{ ${parts.join(", ")} }`;
}

/**
 * One `key: shape,` row. Short rows stay on one line; longer ones expand to one
 * property per line, which is what the formatter does to a group that cannot
 * fit.
 */
function shapeRow(key: string, entry: CatalogEntry): string {
  const flat = `  ${key}: ${shapeFlat(entry)},`;
  if (fits(flat)) return flat;
  const props = [`o: ${literal(entry.outline)},`];
  if (!entry.filledIsOutline) props.push(`f: ${literal(entry.filled)},`);
  if (entry.fillRule) props.push(`r: "evenodd",`);
  return [`  ${key}: {`, ...props.map((p) => `    ${p}`), "  },"].join("\n");
}

/**
 * A `const NAMES = [...] as const` array: flat when the whole statement fits,
 * one name per line otherwise.
 */
function nameArray(constName: string, names: ReadonlyArray<string>): string {
  const flat = `export const ${constName} = [${names.map((n) => literal(n)).join(", ")}] as const;`;
  if (fits(flat)) return flat;
  const rows = names.map((n) => `  ${literal(n)},`);
  return [`export const ${constName} = [`, ...rows, "] as const;"].join("\n");
}

// ---------------------------------------------------------------------------
// symbols / names / manifest
// ---------------------------------------------------------------------------

function emitSymbols(catalog: Catalog): string {
  const rows = catalog.symbols.map((s) => `  | ${literal(s)}`);
  return [
    BANNER("Material Symbols glyph names"),
    "/**",
    " * Every Material Symbols glyph name in the synced upstream catalog",
    " * (snake_case, FILL 0 + FILL 1). The full, ungated name contract.",
    " */",
    "export type MaterialSymbolsName =",
    `${rows.join("\n")};`,
    "",
  ].join("\n");
}

function emitNames(catalog: Catalog): string {
  const names = catalog.entries.map((e) => e.name);
  const material = names.filter(
    (n) => catalog.byName.get(n)?.origin === "material",
  );
  const brand = names.filter((n) => catalog.byName.get(n)?.origin === "brand");

  return [
    BANNER("icon names"),
    "/**",
    " * Every icon name that has local shape data committed in this repository.",
    " *",
    " * Derived from the catalog rather than hand-maintained: `config/kern-icon-set.txt`",
    " * (Material Symbols Rounded) plus every SVG in `assets/brand/`.",
    " */",
    nameArray("ICON_NAMES", names),
    "",
    "/** Canonical icon name. Kebab-case, ASCII, may start with a digit. */",
    "export type IconName = (typeof ICON_NAMES)[number];",
    "",
    "/** Names sourced from Material Symbols Rounded (FILL 0 + FILL 1). */",
    nameArray("MATERIAL_ICON_NAMES", material),
    "",
    "export type MaterialIconName = (typeof MATERIAL_ICON_NAMES)[number];",
    "",
    "/** Names sourced from `assets/brand/` — custom icons. */",
    nameArray("BRAND_ICON_NAMES", brand),
    "",
    "export type BrandIconName = (typeof BRAND_ICON_NAMES)[number];",
    "",
    "const ICON_NAME_SET: ReadonlySet<string> = new Set(ICON_NAMES);",
    "",
    "/** Runtime guard for dynamic icon names (config-driven UI, server payloads). */",
    "export function isIconName(value: unknown): value is IconName {",
    '  return typeof value === "string" && ICON_NAME_SET.has(value);',
    "}",
    "",
    "/** Total number of icons with committed shape data. */",
    `export const ICON_COUNT = ${names.length};`,
    "",
  ].join("\n");
}

function emitManifest(
  catalog: Catalog,
  source: SourceConfig,
  weights: ReadonlyArray<number>,
): string {
  const material = catalog.entries.filter(
    (e) => e.origin === "material",
  ).length;
  const brand = catalog.entries.filter((e) => e.origin === "brand").length;
  const filledReusesOutline = catalog.entries.filter(
    (e) => e.filledIsOutline,
  ).length;

  return [
    BANNER("catalog manifest"),
    'import type { IconManifest } from "../../core/types";',
    "",
    "/**",
    " * Provenance for the committed shape data. Deliberately free of timestamps so",
    " * regeneration is byte-identical and `tools/check.ts` can diff it.",
    " */",
    "export const ICON_MANIFEST: IconManifest = {",
    `  viewBox: ${literal(VIEW_BOX)},`,
    `  precision: ${ICON_SPEC.precision},`,
    `  weights: [${weights.join(", ")}],`,
    `  defaultWeight: ${source.weight},`,
    "  counts: {",
    `    total: ${catalog.entries.length},`,
    `    material: ${material},`,
    `    brand: ${brand},`,
    `    filledReusesOutline: ${filledReusesOutline},`,
    "  },",
    "  source: {",
    `    package: ${literal(source.package)},`,
    `    version: ${literal(source.version)},`,
    `    style: ${literal(source.style)},`,
    `    weight: ${source.weight},`,
    `    opticalSize: ${ICON_SPEC.opticalSize},`,
    `    license: ${literal(source.license)},`,
    `    licenseUrl: ${literal(source.licenseUrl)},`,
    "  },",
    "};",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// shape registry (chunked per weight)
// ---------------------------------------------------------------------------

function emitShapes(catalog: Catalog, weight: number): Map<string, string> {
  const files = new Map<string, string>();

  const byChunk = new Map<string, Array<CatalogEntry>>();
  for (const entry of catalog.entries) {
    const chunk = toChunkId(entry.name);
    const bucket = byChunk.get(chunk);
    if (bucket) bucket.push(entry);
    else byChunk.set(chunk, [entry]);
  }

  const usedChunks: Array<string> = [];
  for (const chunkId of CHUNK_IDS) {
    const entries = byChunk.get(chunkId);
    if (!entries || entries.length === 0) continue;
    usedChunks.push(chunkId);

    const sorted = [...entries].sort((a, b) =>
      compareIconNames(a.name, b.name),
    );
    const rows = sorted.map((e) => shapeRow(toObjectKey(e.name), e));

    files.set(
      `src/sets/material/shapes/w${weight}/${chunkId}.ts`,
      [
        BANNER(`shape chunk "${chunkId}" @ weight ${weight}`),
        'import type { IconWeightShapeMap } from "../../../../core/types";',
        "",
        "export const shapes: IconWeightShapeMap = {",
        ...rows,
        "};",
        "",
      ].join("\n"),
    );
  }

  // Import order matches the formatter: lexicographic by specifier, which puts
  // `../../../../core/types` first and the `./…` chunks in chunk-id order.
  const local = (c: string) => `chunk${c === "0" ? "Zero" : c.toUpperCase()}`;
  const imports = [
    'import type { IconShapeMap } from "../../../../core/types";',
    ...usedChunks.map(
      (c) => `import { shapes as ${local(c)} } from ${literal(`./${c}`)};`,
    ),
  ];
  const spreads = usedChunks.map((c) => `  ...${local(c)},`);

  files.set(
    `src/sets/material/shapes/w${weight}/index.ts`,
    [
      BANNER(`weight ${weight} registry`),
      ...imports,
      "",
      "/**",
      ` * Every shape for weight ${weight}, keyed by icon name.`,
      " *",
      " * Chunked by first character so a bundle that only ever renders icons from a",
      " * known slice can be code-split; a dynamic `<Icon name={…} />` pulls the",
      " * whole weight, which is why `config/kern-icon-set.txt` stays curated.",
      " */",
      "export const shapes: IconShapeMap = {",
      ...spreads,
      "};",
      "",
    ].join("\n"),
  );

  return files;
}

function emitShapeRegistry(
  catalog: Catalog,
  weights: ReadonlyArray<number>,
): Map<string, string> {
  const files = new Map<string, string>();

  for (const w of weights) {
    for (const [rel, contents] of emitShapes(catalog, w))
      files.set(rel, contents);
  }

  const importLines = weights
    .map((w) => `import { shapes as w${w} } from ${literal(`./w${w}`)};`)
    .sort();
  const entries = weights.map((w) => `  ${w}: w${w},`);

  files.set(
    "src/sets/material/shapes/index.ts",
    [
      BANNER("shape registry"),
      'import type { IconWeight, IconWeightRegistry } from "../../../core/types";',
      ...importLines,
      "",
      "/** Shape data by Material Symbols weight axis value. */",
      "export const ICON_SHAPES: IconWeightRegistry = {",
      ...entries,
      "};",
      "",
      "/** Weights that have local shape data. */",
      `export const ICON_WEIGHTS = [${weights.join(", ")}] as const satisfies readonly IconWeight[];`,
      "",
    ].join("\n"),
  );

  return files;
}

// ---------------------------------------------------------------------------
// extra sets
// ---------------------------------------------------------------------------

function emitExtraSets(): string {
  return [
    BANNER("extra icon sets"),
    'import type { IconSet } from "../core/types";',
    "",
    "/**",
    " * Drop-in icon sets discovered under `assets/sets/`, keyed by set id.",
    " *",
    " * The default set is registered from `src/sets/material/`; everything here is",
    " * additive and arrives through `registerIconSet` at load.",
    " */",
    "export const EXTRA_SETS: Readonly<Record<string, IconSet>> = {};",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------

export interface EmitOptions {
  readonly weights: ReadonlyArray<number>;
}

/** Generated file map: package-relative path → contents. */
export type EmitResult = ReadonlyMap<string, string>;

export function emitAll(catalog: Catalog, options: EmitOptions): EmitResult {
  const source = readSourceConfig();
  const files = new Map<string, string>();

  files.set("src/sets/material/symbols.ts", emitSymbols(catalog));
  files.set("src/sets/material/names.ts", emitNames(catalog));
  files.set(
    "src/sets/material/manifest.ts",
    emitManifest(catalog, source, options.weights),
  );
  for (const [rel, contents] of emitShapeRegistry(catalog, options.weights)) {
    files.set(rel, contents);
  }
  files.set("src/sets/index.ts", emitExtraSets());

  return files;
}
