// AUTO-GENERATED by tools/generate.ts — extra icon sets.
// Do not edit by hand. Change the assets or config and re-run:
//   bun run generate

import type { IconSet } from "../core/types";

/**
 * Drop-in icon sets discovered under `assets/sets/`, keyed by set id.
 *
 * The default set is registered from `src/sets/material/`; everything here is
 * additive and arrives through `registerIconSet` at load.
 */
export const EXTRA_SETS: Readonly<Record<string, IconSet>> = {};
