// GENERATED by scripts/generate-manifest.mjs — do not hand-edit.
export type ComponentStatus = "real" | "stub";

export type ComponentEntry = {
  name: string;
  export: string;
  platform: "web" | "native";
  path: string;
  status: ComponentStatus;
};

export const COMPONENTS: ComponentEntry[] = [
  {
    name: "badge",
    export: "Badge",
    platform: "web",
    path: "src/react/components/badge.tsx",
    status: "real",
  },
  {
    name: "button",
    export: "Button",
    platform: "web",
    path: "src/react/components/button.tsx",
    status: "real",
  },
  {
    name: "card",
    export: "Card",
    platform: "web",
    path: "src/react/components/card.tsx",
    status: "real",
  },
  {
    name: "checkbox",
    export: "Checkbox",
    platform: "web",
    path: "src/react/components/checkbox.tsx",
    status: "real",
  },
  {
    name: "chip",
    export: "Chip",
    platform: "web",
    path: "src/react/components/chip.tsx",
    status: "real",
  },
  {
    name: "field-message",
    export: "FieldMessage",
    platform: "web",
    path: "src/react/components/field-message.tsx",
    status: "real",
  },
  {
    name: "input",
    export: "Input",
    platform: "web",
    path: "src/react/components/input.tsx",
    status: "real",
  },
  {
    name: "label",
    export: "Label",
    platform: "web",
    path: "src/react/components/label.tsx",
    status: "real",
  },
  {
    name: "radio-group",
    export: "RadioGroup",
    platform: "web",
    path: "src/react/components/radio-group.tsx",
    status: "real",
  },
  {
    name: "separator",
    export: "Separator",
    platform: "web",
    path: "src/react/components/separator.tsx",
    status: "real",
  },
  {
    name: "switch",
    export: "Switch",
    platform: "web",
    path: "src/react/components/switch.tsx",
    status: "real",
  },
  {
    name: "text",
    export: "Text",
    platform: "web",
    path: "src/react/components/text.tsx",
    status: "real",
  },
  {
    name: "textarea",
    export: "Textarea",
    platform: "web",
    path: "src/react/components/textarea.tsx",
    status: "real",
  },
  {
    name: "badge",
    export: "Badge",
    platform: "native",
    path: "src/react-native/components/badge.tsx",
    status: "stub",
  },
  {
    name: "card",
    export: "Card",
    platform: "native",
    path: "src/react-native/components/card.tsx",
    status: "stub",
  },
  {
    name: "checkbox",
    export: "Checkbox",
    platform: "native",
    path: "src/react-native/components/checkbox.tsx",
    status: "stub",
  },
  {
    name: "chip",
    export: "Chip",
    platform: "native",
    path: "src/react-native/components/chip.tsx",
    status: "stub",
  },
  {
    name: "divider",
    export: "Divider",
    platform: "native",
    path: "src/react-native/components/divider.tsx",
    status: "stub",
  },
  {
    name: "field-message",
    export: "FieldMessage",
    platform: "native",
    path: "src/react-native/components/field-message.tsx",
    status: "stub",
  },
  {
    name: "input",
    export: "Input",
    platform: "native",
    path: "src/react-native/components/input.tsx",
    status: "stub",
  },
  {
    name: "list-item",
    export: "ListItem",
    platform: "native",
    path: "src/react-native/components/list-item.tsx",
    status: "stub",
  },
  {
    name: "radio",
    export: "Radio",
    platform: "native",
    path: "src/react-native/components/radio.tsx",
    status: "stub",
  },
  {
    name: "switch",
    export: "Switch",
    platform: "native",
    path: "src/react-native/components/switch.tsx",
    status: "stub",
  },
  {
    name: "text",
    export: "Text",
    platform: "native",
    path: "src/react-native/components/text.tsx",
    status: "stub",
  },
  {
    name: "button",
    export: "Button",
    platform: "native",
    path: "src/react-native/index.ts",
    status: "stub",
  },
];
