// GENERATED from stub inventory — do not hand-edit entries.
// Regenerate when stubs change. Statuses: real | stub | tangled | review.
export type ComponentStatus = "real" | "stub" | "tangled" | "review";

export type ComponentEntry = {
  name: string;
  export: string;
  platform: "web" | "native";
  path: string;
  status: ComponentStatus;
  source: string;
};

export const COMPONENTS: ComponentEntry[] = [
  {
    name: "alert-dialog",
    export: "AlertDialog",
    platform: "web",
    path: "src/web/components/alert-dialog.tsx",
    status: "stub",
  },
  {
    name: "alert",
    export: "Alert",
    platform: "web",
    path: "src/web/components/alert.tsx",
    status: "stub",
  },
  {
    name: "avatar",
    export: "Avatar",
    platform: "web",
    path: "src/web/components/avatar.tsx",
    status: "stub",
  },
  {
    name: "badge",
    export: "Badge",
    platform: "web",
    path: "src/web/components/badge.tsx",
    status: "stub",
  },
  {
    name: "card",
    export: "Card",
    platform: "web",
    path: "src/web/components/card.tsx",
    status: "stub",
  },
  {
    name: "checkbox",
    export: "Checkbox",
    platform: "web",
    path: "src/web/components/checkbox.tsx",
    status: "stub",
  },
  {
    name: "chip",
    export: "Chip",
    platform: "web",
    path: "src/web/components/chip.tsx",
    status: "stub",
  },
  {
    name: "collapsible",
    export: "Collapsible",
    platform: "web",
    path: "src/web/components/collapsible.tsx",
    status: "stub",
  },
  {
    name: "command",
    export: "Command",
    platform: "web",
    path: "src/web/components/command.tsx",
    status: "stub",
  },
  {
    name: "context-menu",
    export: "ContextMenu",
    platform: "web",
    path: "src/web/components/context-menu.tsx",
    status: "stub",
  },
  {
    name: "country-select",
    export: "CountrySelect",
    platform: "web",
    path: "src/web/components/country-select.tsx",
    status: "tangled",
  },
  {
    name: "dialog",
    export: "Dialog",
    platform: "web",
    path: "src/web/components/dialog.tsx",
    status: "stub",
  },
  {
    name: "dropdown-menu",
    export: "DropdownMenu",
    platform: "web",
    path: "src/web/components/dropdown-menu.tsx",
    status: "stub",
  },
  {
    name: "fab",
    export: "FAB",
    platform: "web",
    path: "src/web/components/fab.tsx",
    status: "stub",
  },
  {
    name: "field-message",
    export: "FieldMessage",
    platform: "web",
    path: "src/web/components/field-message.tsx",
    status: "stub",
  },
  {
    name: "input",
    export: "Input",
    platform: "web",
    path: "src/web/components/input.tsx",
    status: "stub",
  },
  {
    name: "input-otp",
    export: "InputOTP",
    platform: "web",
    path: "src/web/components/input-otp.tsx",
    status: "stub",
  },
  {
    name: "label",
    export: "Label",
    platform: "web",
    path: "src/web/components/label.tsx",
    status: "stub",
  },
  {
    name: "list-item",
    export: "ListItem",
    platform: "web",
    path: "src/web/components/list-item.tsx",
    status: "stub",
  },
  {
    name: "native-select",
    export: "NativeSelect",
    platform: "web",
    path: "src/web/components/native-select.tsx",
    status: "stub",
  },
  {
    name: "popover",
    export: "Popover",
    platform: "web",
    path: "src/web/components/popover.tsx",
    status: "stub",
  },
  {
    name: "radio-group",
    export: "RadioGroup",
    platform: "web",
    path: "src/web/components/radio-group.tsx",
    status: "stub",
  },
  {
    name: "scroll-area",
    export: "ScrollArea",
    platform: "web",
    path: "src/web/components/scroll-area.tsx",
    status: "stub",
  },
  {
    name: "segmented-button",
    export: "SegmentedButton",
    platform: "web",
    path: "src/web/components/segmented-button.tsx",
    status: "stub",
  },
  {
    name: "separator",
    export: "Separator",
    platform: "web",
    path: "src/web/components/separator.tsx",
    status: "stub",
  },
  {
    name: "sheet",
    export: "Sheet",
    platform: "web",
    path: "src/web/components/sheet.tsx",
    status: "stub",
  },
  {
    name: "select",
    export: "Select",
    platform: "web",
    path: "src/web/components/select.tsx",
    status: "stub",
  },
  {
    name: "slider",
    export: "Slider",
    platform: "web",
    path: "src/web/components/slider.tsx",
    status: "stub",
  },
  {
    name: "sonner",
    export: "Toaster",
    platform: "web",
    path: "src/web/components/sonner.tsx",
    status: "stub",
  },
  {
    name: "switch",
    export: "Switch",
    platform: "web",
    path: "src/web/components/switch.tsx",
    status: "stub",
  },
  {
    name: "table",
    export: "Table",
    platform: "web",
    path: "src/web/components/table.tsx",
    status: "stub",
  },
  {
    name: "tabs",
    export: "Tabs",
    platform: "web",
    path: "src/web/components/tabs.tsx",
    status: "stub",
  },
  {
    name: "text",
    export: "Text",
    platform: "web",
    path: "src/web/components/text.tsx",
    status: "stub",
  },
  {
    name: "textarea",
    export: "Textarea",
    platform: "web",
    path: "src/web/components/textarea.tsx",
    status: "stub",
  },
  {
    name: "title",
    export: "Title",
    platform: "web",
    path: "src/web/components/title.tsx",
    status: "stub",
  },
  {
    name: "tooltip",
    export: "Tooltip",
    platform: "web",
    path: "src/web/components/tooltip.tsx",
    status: "stub",
  },
  {
    name: "app-search-bar",
    export: "AppSearchBar",
    platform: "native",
    path: "src/native/components/app-search-bar.tsx",
    status: "stub",
  },
  {
    name: "banner",
    export: "Banner",
    platform: "native",
    path: "src/native/components/banner.tsx",
    status: "stub",
  },
  {
    name: "badge",
    export: "Badge",
    platform: "native",
    path: "src/native/components/badge.tsx",
    status: "stub",
  },
  {
    name: "bottom-navigation",
    export: "BottomNavigation",
    platform: "native",
    path: "src/native/components/bottom-navigation.tsx",
    status: "stub",
  },
  {
    name: "bottom-sheet",
    export: "BottomSheet",
    platform: "native",
    path: "src/native/components/bottom-sheet.tsx",
    status: "stub",
  },
  {
    name: "bottom-sheet-picker",
    export: "BottomSheetPicker",
    platform: "native",
    path: "src/native/components/bottom-sheet-picker.tsx",
    status: "stub",
  },
  {
    name: "calendar",
    export: "Calendar",
    platform: "native",
    path: "src/native/components/calendar.tsx",
    status: "stub",
  },
  {
    name: "card",
    export: "Card",
    platform: "native",
    path: "src/native/components/card.tsx",
    status: "stub",
  },
  {
    name: "carousel",
    export: "Carousel",
    platform: "native",
    path: "src/native/components/carousel.tsx",
    status: "stub",
  },
  {
    name: "chart",
    export: "Chart",
    platform: "native",
    path: "src/native/components/chart.tsx",
    status: "stub",
  },
  {
    name: "checkbox",
    export: "Checkbox",
    platform: "native",
    path: "src/native/components/checkbox.tsx",
    status: "stub",
  },
  {
    name: "chip",
    export: "Chip",
    platform: "native",
    path: "src/native/components/chip.tsx",
    status: "stub",
  },
  {
    name: "confirm-dialog",
    export: "ConfirmDialog",
    platform: "native",
    path: "src/native/components/confirm-dialog.tsx",
    status: "stub",
  },
  {
    name: "contact-row",
    export: "ContactRow",
    platform: "native",
    path: "src/native/components/contact-row.tsx",
    status: "review",
  },
  {
    name: "context-selector",
    export: "ContextSelector",
    platform: "native",
    path: "src/native/components/context-selector.tsx",
    status: "stub",
  },
  {
    name: "conversation-row",
    export: "ConversationRow",
    platform: "native",
    path: "src/native/components/conversation-row.tsx",
    status: "review",
  },
  {
    name: "country-select",
    export: "CountrySelect",
    platform: "native",
    path: "src/native/components/country-select.tsx",
    status: "tangled",
  },
  {
    name: "data-table",
    export: "DataTable",
    platform: "native",
    path: "src/native/components/data-table.tsx",
    status: "stub",
  },
  {
    name: "divider",
    export: "Divider",
    platform: "native",
    path: "src/native/components/divider.tsx",
    status: "stub",
  },
  {
    name: "dock-sheet/dock-sheet",
    export: "DockSheet",
    platform: "native",
    path: "src/native/components/dock-sheet/dock-sheet.tsx",
    status: "stub",
  },
  {
    name: "dock-sheet/grid",
    export: "DockSheetGrid",
    platform: "native",
    path: "src/native/components/dock-sheet/grid.tsx",
    status: "stub",
  },
  {
    name: "dock-sheet/tile",
    export: "DockSheetTile",
    platform: "native",
    path: "src/native/components/dock-sheet/tile.tsx",
    status: "stub",
  },
  {
    name: "dropdown",
    export: "Dropdown",
    platform: "native",
    path: "src/native/components/dropdown.tsx",
    status: "stub",
  },
  {
    name: "empty-state",
    export: "EmptyState",
    platform: "native",
    path: "src/native/components/empty-state.tsx",
    status: "stub",
  },
  {
    name: "entity-sheet",
    export: "EntitySheet",
    platform: "native",
    path: "src/native/components/entity-sheet.tsx",
    status: "review",
  },
  {
    name: "fab",
    export: "Fab",
    platform: "native",
    path: "src/native/components/fab.tsx",
    status: "stub",
  },
  {
    name: "field-message",
    export: "FieldMessage",
    platform: "native",
    path: "src/native/components/field-message.tsx",
    status: "stub",
  },
  {
    name: "flat-list",
    export: "FlatList",
    platform: "native",
    path: "src/native/components/flat-list.tsx",
    status: "stub",
  },
  {
    name: "floating-fab",
    export: "FloatingFab",
    platform: "native",
    path: "src/native/components/floating-fab.tsx",
    status: "stub",
  },
  {
    name: "floating-tabs",
    export: "FloatingTabs",
    platform: "native",
    path: "src/native/components/floating-tabs.tsx",
    status: "stub",
  },
  {
    name: "input",
    export: "Input",
    platform: "native",
    path: "src/native/components/input.tsx",
    status: "stub",
  },
  {
    name: "list",
    export: "List",
    platform: "native",
    path: "src/native/components/list.tsx",
    status: "stub",
  },
  {
    name: "list-item",
    export: "ListItem",
    platform: "native",
    path: "src/native/components/list-item.tsx",
    status: "stub",
  },
  {
    name: "list-separator",
    export: "ListSeparator",
    platform: "native",
    path: "src/native/components/list-separator.tsx",
    status: "stub",
  },
  {
    name: "menu-list",
    export: "MenuList",
    platform: "native",
    path: "src/native/components/menu-list.tsx",
    status: "stub",
  },
  {
    name: "modal",
    export: "Modal",
    platform: "native",
    path: "src/native/components/modal.tsx",
    status: "stub",
  },
  {
    name: "outlined-icon-button",
    export: "OutlinedIconButton",
    platform: "native",
    path: "src/native/components/outlined-icon-button.tsx",
    status: "stub",
  },
  {
    name: "placeholder-screen",
    export: "PlaceholderScreen",
    platform: "native",
    path: "src/native/components/placeholder-screen.tsx",
    status: "stub",
  },
  {
    name: "portal",
    export: "Portal",
    platform: "native",
    path: "src/native/components/portal.tsx",
    status: "stub",
  },
  {
    name: "progress-bar",
    export: "ProgressBar",
    platform: "native",
    path: "src/native/components/progress-bar.tsx",
    status: "stub",
  },
  {
    name: "radio",
    export: "Radio",
    platform: "native",
    path: "src/native/components/radio.tsx",
    status: "stub",
  },
  {
    name: "searchbar",
    export: "Searchbar",
    platform: "native",
    path: "src/native/components/searchbar.tsx",
    status: "stub",
  },
  {
    name: "section-header",
    export: "SectionHeader",
    platform: "native",
    path: "src/native/components/section-header.tsx",
    status: "stub",
  },
  {
    name: "section-label",
    export: "SectionLabel",
    platform: "native",
    path: "src/native/components/section-label.tsx",
    status: "stub",
  },
  {
    name: "section-list",
    export: "SectionList",
    platform: "native",
    path: "src/native/components/section-list.tsx",
    status: "stub",
  },
  {
    name: "segmented-buttons",
    export: "SegmentedButtons",
    platform: "native",
    path: "src/native/components/segmented-buttons.tsx",
    status: "stub",
  },
  {
    name: "skeleton",
    export: "Skeleton",
    platform: "native",
    path: "src/native/components/skeleton.tsx",
    status: "stub",
  },
  {
    name: "sliders-icon",
    export: "SlidersIcon",
    platform: "native",
    path: "src/native/components/sliders-icon.tsx",
    status: "stub",
  },
  {
    name: "snackbar",
    export: "Snackbar",
    platform: "native",
    path: "src/native/components/snackbar.tsx",
    status: "stub",
  },
  {
    name: "snap-sheet",
    export: "SnapSheet",
    platform: "native",
    path: "src/native/components/snap-sheet.tsx",
    status: "stub",
  },
  {
    name: "splash",
    export: "Splash",
    platform: "native",
    path: "src/native/components/splash.tsx",
    status: "stub",
  },
  {
    name: "spinner",
    export: "Spinner",
    platform: "native",
    path: "src/native/components/spinner.tsx",
    status: "stub",
  },
  {
    name: "surface",
    export: "Surface",
    platform: "native",
    path: "src/native/components/surface.tsx",
    status: "stub",
  },
  {
    name: "switch",
    export: "Switch",
    platform: "native",
    path: "src/native/components/switch.tsx",
    status: "stub",
  },
  {
    name: "tabs",
    export: "Tabs",
    platform: "native",
    path: "src/native/components/tabs.tsx",
    status: "stub",
  },
  {
    name: "text",
    export: "Text",
    platform: "native",
    path: "src/native/components/text.tsx",
    status: "stub",
  },
  {
    name: "toggle-button",
    export: "ToggleButton",
    platform: "native",
    path: "src/native/components/toggle-button.tsx",
    status: "stub",
  },
  {
    name: "toolbar-button",
    export: "ToolbarButton",
    platform: "native",
    path: "src/native/components/toolbar-button.tsx",
    status: "stub",
  },
  {
    name: "tooltip",
    export: "Tooltip",
    platform: "native",
    path: "src/native/components/tooltip.tsx",
    status: "stub",
  },
  {
    name: "button",
    export: "Button",
    platform: "native",
    path: "src/native/index.ts",
    status: "stub",
  },
];
