// GENERATED by packages/mcp/scripts/generate-maturity.mjs — do not hand-edit.
//
// The ONE source the site's maturity chips read. Derived from package metadata
// (version, deprecated) and registry status (real | stub) — never hand-typed,
// because a hand-typed table is a second opinion that drifts from the packages
// it describes.
//
// Today every package is 0.0.0, so every real export is "Preview". That is a
// measured result, not a placeholder: bump a package past 0.x and this file
// changes with no code edit.
export type MaturityState =
  | "Preview"
  | "Stable"
  | "Maintained"
  | "Sunsetting"
  | "Archived";

export type MaturityRow = {
  name: string;
  export: string;
  platform: "web" | "native";
  state: MaturityState;
  version: string;
};

/** Every registry export, with its derived maturity. */
export const MATURITY: readonly MaturityRow[] = [
  {
    "name": "accordion-root",
    "export": "AccordionRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "accordion-item",
    "export": "AccordionItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "accordion-header",
    "export": "AccordionHeader",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "accordion-trigger",
    "export": "AccordionTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "accordion-panel",
    "export": "AccordionPanel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "accordion",
    "export": "Accordion",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "alert-dialog-root",
    "export": "AlertDialogRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "alert-dialog-trigger",
    "export": "AlertDialogTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "alert-dialog-content",
    "export": "AlertDialogContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "alert-dialog-title",
    "export": "AlertDialogTitle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "alert-dialog-description",
    "export": "AlertDialogDescription",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "alert-dialog-close",
    "export": "AlertDialogClose",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "alert-dialog",
    "export": "AlertDialog",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "autocomplete-root",
    "export": "AutocompleteRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "autocomplete-label",
    "export": "AutocompleteLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "autocomplete-input",
    "export": "AutocompleteInput",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "autocomplete-content",
    "export": "AutocompleteContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "autocomplete-item",
    "export": "AutocompleteItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "autocomplete-empty",
    "export": "AutocompleteEmpty",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "autocomplete",
    "export": "Autocomplete",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "avatar-root",
    "export": "AvatarRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "avatar-image",
    "export": "AvatarImage",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "avatar-fallback",
    "export": "AvatarFallback",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "avatar",
    "export": "Avatar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "badge",
    "export": "Badge",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "banner",
    "export": "Banner",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "banner-action",
    "export": "BannerAction",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "boot-indicator",
    "export": "BootIndicator",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "button-group",
    "export": "ButtonGroup",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "button",
    "export": "Button",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "calendar",
    "export": "Calendar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "card",
    "export": "Card",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "carousel",
    "export": "Carousel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "checkbox-group-root",
    "export": "CheckboxGroupRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "checkbox-group-item",
    "export": "CheckboxGroupItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "checkbox-group",
    "export": "CheckboxGroup",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "checkbox",
    "export": "Checkbox",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "chip",
    "export": "Chip",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "circular-progress",
    "export": "CircularProgress",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "collapsible-root",
    "export": "CollapsibleRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "collapsible-trigger",
    "export": "CollapsibleTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "collapsible-panel",
    "export": "CollapsiblePanel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "collapsible",
    "export": "Collapsible",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "combobox-root",
    "export": "ComboboxRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "combobox-label",
    "export": "ComboboxLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "combobox-input",
    "export": "ComboboxInput",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "combobox-trigger",
    "export": "ComboboxTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "combobox-clear",
    "export": "ComboboxClear",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "combobox-content",
    "export": "ComboboxContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "combobox-item",
    "export": "ComboboxItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "combobox-empty",
    "export": "ComboboxEmpty",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "combobox",
    "export": "Combobox",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command-root",
    "export": "CommandRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command-input",
    "export": "CommandInput",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command-content",
    "export": "CommandContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command-list",
    "export": "CommandList",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command-item",
    "export": "CommandItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command-empty",
    "export": "CommandEmpty",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command-separator",
    "export": "CommandSeparator",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command-group-label",
    "export": "CommandGroupLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command",
    "export": "Command",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "context-menu-root",
    "export": "ContextMenuRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "context-menu-trigger",
    "export": "ContextMenuTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "context-menu-content",
    "export": "ContextMenuContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "context-menu-item",
    "export": "ContextMenuItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "context-menu-separator",
    "export": "ContextMenuSeparator",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "context-menu",
    "export": "ContextMenu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "country-select-root",
    "export": "CountrySelectRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "country-select-label",
    "export": "CountrySelectLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "country-select-trigger",
    "export": "CountrySelectTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "country-select-value",
    "export": "CountrySelectValue",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "country-select-content",
    "export": "CountrySelectContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "country-select-item",
    "export": "CountrySelectItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "country-select",
    "export": "CountrySelect",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dialog-root",
    "export": "DialogRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dialog-trigger",
    "export": "DialogTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dialog-content",
    "export": "DialogContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dialog-title",
    "export": "DialogTitle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dialog-description",
    "export": "DialogDescription",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dialog-close",
    "export": "DialogClose",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dialog",
    "export": "Dialog",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "drawer-root",
    "export": "DrawerRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "drawer-trigger",
    "export": "DrawerTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "drawer-content",
    "export": "DrawerContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "drawer-title",
    "export": "DrawerTitle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "drawer-description",
    "export": "DrawerDescription",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "drawer-close",
    "export": "DrawerClose",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "drawer",
    "export": "Drawer",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "empty-state",
    "export": "EmptyState",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "kern-error-boundary",
    "export": "KernErrorBoundary",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "extended-fab",
    "export": "ExtendedFab",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fab-menu",
    "export": "FabMenu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fab",
    "export": "Fab",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "field-message",
    "export": "FieldMessage",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "field-root",
    "export": "FieldRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "field-label",
    "export": "FieldLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "field-description",
    "export": "FieldDescription",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "field-error",
    "export": "FieldError",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "field",
    "export": "Field",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fieldset-root",
    "export": "FieldsetRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fieldset-legend",
    "export": "FieldsetLegend",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fieldset",
    "export": "Fieldset",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "form",
    "export": "Form",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "icon-button",
    "export": "IconButton",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "input-otp-root",
    "export": "InputOTPRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "input-otp-input",
    "export": "InputOTPInput",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "input-otp",
    "export": "InputOTP",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "input",
    "export": "Input",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "kbd",
    "export": "Kbd",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "label",
    "export": "Label",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "linear-progress",
    "export": "LinearProgress",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "list-item",
    "export": "ListItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "loader",
    "export": "Loader",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "loading-button",
    "export": "LoadingButton",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "loading-indicator",
    "export": "LoadingIndicator",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "loading-region",
    "export": "LoadingRegion",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-screen",
    "export": "MenuScreen",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-sheet",
    "export": "MenuSheet",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "filter-chip-row",
    "export": "FilterChipRow",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-root",
    "export": "MenuRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-trigger",
    "export": "MenuTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-content",
    "export": "MenuContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-item",
    "export": "MenuItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-separator",
    "export": "MenuSeparator",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-group-label",
    "export": "MenuGroupLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu",
    "export": "Menu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menubar-root",
    "export": "MenubarRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menubar-menu",
    "export": "MenubarMenu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menubar-trigger",
    "export": "MenubarTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menubar-content",
    "export": "MenubarContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menubar-item",
    "export": "MenubarItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menubar",
    "export": "Menubar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "meter-root",
    "export": "MeterRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "meter-label",
    "export": "MeterLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "meter-value",
    "export": "MeterValue",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "meter",
    "export": "Meter",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "native-select",
    "export": "NativeSelect",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-bar",
    "export": "NavigationBar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-bar-item",
    "export": "NavigationBarItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-drawer",
    "export": "NavigationDrawer",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-menu-root",
    "export": "NavigationMenuRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-menu-list",
    "export": "NavigationMenuList",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-menu-item",
    "export": "NavigationMenuItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-menu-trigger",
    "export": "NavigationMenuTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-menu-content",
    "export": "NavigationMenuContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-menu-link",
    "export": "NavigationMenuLink",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-menu",
    "export": "NavigationMenu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "number-field-root",
    "export": "NumberFieldRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "number-field-input",
    "export": "NumberFieldInput",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "number-field",
    "export": "NumberField",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "page-loader",
    "export": "PageLoader",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "pagination",
    "export": "Pagination",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "popover-root",
    "export": "PopoverRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "popover-trigger",
    "export": "PopoverTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "popover-content",
    "export": "PopoverContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "popover-title",
    "export": "PopoverTitle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "popover-description",
    "export": "PopoverDescription",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "popover-close",
    "export": "PopoverClose",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "popover",
    "export": "Popover",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "preview-card-root",
    "export": "PreviewCardRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "preview-card-trigger",
    "export": "PreviewCardTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "preview-card-content",
    "export": "PreviewCardContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "preview-card",
    "export": "PreviewCard",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "progress-root",
    "export": "ProgressRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "progress-label",
    "export": "ProgressLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "progress-value",
    "export": "ProgressValue",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "progress",
    "export": "Progress",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "radio-group",
    "export": "RadioGroup",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "radio-group-item",
    "export": "RadioGroupItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "scroll-area-root",
    "export": "ScrollAreaRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "scroll-area-viewport",
    "export": "ScrollAreaViewport",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "scroll-area-scrollbar",
    "export": "ScrollAreaScrollbar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "scroll-area",
    "export": "ScrollArea",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "search",
    "export": "Search",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "secondary-tabs",
    "export": "SecondaryTabs",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "segmented-button-root",
    "export": "SegmentedButtonRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "segmented-button-item",
    "export": "SegmentedButtonItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "segmented-button",
    "export": "SegmentedButton",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select-root",
    "export": "SelectRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select-trigger",
    "export": "SelectTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select-value",
    "export": "SelectValue",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select-content",
    "export": "SelectContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select-item",
    "export": "SelectItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select-item-text",
    "export": "SelectItemText",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select-separator",
    "export": "SelectSeparator",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select-group-label",
    "export": "SelectGroupLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select",
    "export": "Select",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "separator",
    "export": "Separator",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet-surface",
    "export": "SheetSurface",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "bottom-sheet",
    "export": "BottomSheet",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dock-sheet",
    "export": "DockSheet",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snap-sheet",
    "export": "SnapSheet",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "entity-sheet",
    "export": "EntitySheet",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "bottom-sheet-picker",
    "export": "BottomSheetPicker",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "action-sheet",
    "export": "ActionSheet",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet-root",
    "export": "SheetRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet-trigger",
    "export": "SheetTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet-content",
    "export": "SheetContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet-title",
    "export": "SheetTitle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet-description",
    "export": "SheetDescription",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet-close",
    "export": "SheetClose",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet",
    "export": "Sheet",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "skeleton",
    "export": "Skeleton",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "slider-root",
    "export": "SliderRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "slider-thumb",
    "export": "SliderThumb",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "slider-label",
    "export": "SliderLabel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "slider-value",
    "export": "SliderValue",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "slider",
    "export": "Slider",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar-provider",
    "export": "SnackbarProvider",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar-viewport",
    "export": "SnackbarViewport",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar-root",
    "export": "SnackbarRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar-title",
    "export": "SnackbarTitle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar-description",
    "export": "SnackbarDescription",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar-action",
    "export": "SnackbarAction",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar-close",
    "export": "SnackbarClose",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar-list",
    "export": "SnackbarList",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar",
    "export": "Snackbar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sonner-provider",
    "export": "SonnerProvider",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sonner-viewport",
    "export": "SonnerViewport",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sonner-root",
    "export": "SonnerRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sonner-title",
    "export": "SonnerTitle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sonner-description",
    "export": "SonnerDescription",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sonner-action",
    "export": "SonnerAction",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sonner-close",
    "export": "SonnerClose",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sonner-list",
    "export": "SonnerList",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sonner",
    "export": "Sonner",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "split-button",
    "export": "SplitButton",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "split",
    "export": "Split",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "switch",
    "export": "Switch",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "table-root",
    "export": "TableRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "table-head",
    "export": "TableHead",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "table-body",
    "export": "TableBody",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "table-row",
    "export": "TableRow",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "table-header",
    "export": "TableHeader",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "table-cell",
    "export": "TableCell",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "table-caption",
    "export": "TableCaption",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "table",
    "export": "Table",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tabs-root",
    "export": "TabsRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tabs-list",
    "export": "TabsList",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tabs-tab",
    "export": "TabsTab",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tabs-panel",
    "export": "TabsPanel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tabs",
    "export": "Tabs",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "text",
    "export": "Text",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "textarea",
    "export": "Textarea",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "time-picker",
    "export": "TimePicker",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toggle-group-root",
    "export": "ToggleGroupRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toggle-group-item",
    "export": "ToggleGroupItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toggle-group",
    "export": "ToggleGroup",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toggle",
    "export": "Toggle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toolbar-root",
    "export": "ToolbarRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toolbar-group",
    "export": "ToolbarGroup",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toolbar-button",
    "export": "ToolbarButton",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toolbar-separator",
    "export": "ToolbarSeparator",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toolbar",
    "export": "Toolbar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tooltip-provider",
    "export": "TooltipProvider",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tooltip-root",
    "export": "TooltipRoot",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tooltip-trigger",
    "export": "TooltipTrigger",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tooltip-content",
    "export": "TooltipContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tooltip",
    "export": "Tooltip",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "search-bar",
    "export": "SearchBar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "settings-row",
    "export": "SettingsRow",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "status-bar",
    "export": "StatusBar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "theme-toggle",
    "export": "ThemeToggle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "contrast-toggle",
    "export": "ContrastToggle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "link-provider",
    "export": "LinkProvider",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "link",
    "export": "Link",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sidebar-provider",
    "export": "SidebarProvider",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sidebar",
    "export": "Sidebar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sidebar-header",
    "export": "SidebarHeader",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sidebar-content",
    "export": "SidebarContent",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sidebar-footer",
    "export": "SidebarFooter",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sidebar-item",
    "export": "SidebarItem",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-rail",
    "export": "NavigationRail",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-rail-button",
    "export": "NavigationRailButton",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "section-drawer",
    "export": "SectionDrawer",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "pane",
    "export": "Pane",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "page",
    "export": "Page",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "split-grid",
    "export": "SplitGrid",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "split-panel",
    "export": "SplitPanel",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "list-detail",
    "export": "ListDetail",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "inspector",
    "export": "Inspector",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "app-shell",
    "export": "AppShell",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "document",
    "export": "Document",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "top-app-bar",
    "export": "TopAppBar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "top-app-bar-toggle",
    "export": "TopAppBarToggle",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "app-top-bar",
    "export": "AppTopBar",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "top-bar-menu",
    "export": "TopBarMenu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "apps-menu",
    "export": "AppsMenu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "help-menu",
    "export": "HelpMenu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "notifications-menu",
    "export": "NotificationsMenu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "user-menu",
    "export": "UserMenu",
    "platform": "web",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "accordion",
    "export": "Accordion",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "alert-dialog",
    "export": "AlertDialog",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "app-shell",
    "export": "AppShell",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "aspect-ratio",
    "export": "AspectRatio",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "autocomplete",
    "export": "Autocomplete",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "avatar",
    "export": "Avatar",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "badge",
    "export": "Badge",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "button-group",
    "export": "ButtonGroup",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "button",
    "export": "Button",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "calendar",
    "export": "Calendar",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "card",
    "export": "Card",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "carousel",
    "export": "Carousel",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "checkbox-group",
    "export": "CheckboxGroup",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "checkbox-group-item",
    "export": "CheckboxGroupItem",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "checkbox",
    "export": "Checkbox",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "chip",
    "export": "Chip",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "circular-progress",
    "export": "CircularProgress",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "collapsible",
    "export": "Collapsible",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "context-menu",
    "export": "ContextMenu",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dialog",
    "export": "Dialog",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "empty-state",
    "export": "EmptyState",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "extended-fab",
    "export": "ExtendedFab",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fab-menu",
    "export": "FabMenu",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fab",
    "export": "Fab",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "field-message",
    "export": "FieldMessage",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "field",
    "export": "Field",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "field-root",
    "export": "FieldRoot",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fieldset",
    "export": "Fieldset",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fieldset-legend",
    "export": "FieldsetLegend",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "fieldset-item",
    "export": "FieldsetItem",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "icon-button",
    "export": "IconButton",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "icon-button-target",
    "export": "IconButtonTarget",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "input-otp",
    "export": "InputOTP",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "input",
    "export": "Input",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "label",
    "export": "Label",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "filter-chip-row",
    "export": "FilterChipRow",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "secondary-tabs",
    "export": "SecondaryTabs",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "pane",
    "export": "Pane",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "list-detail",
    "export": "ListDetail",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "supporting-pane",
    "export": "SupportingPane",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "linear-progress",
    "export": "LinearProgress",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "list-item",
    "export": "ListItem",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "loader",
    "export": "Loader",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "loading-button",
    "export": "LoadingButton",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "loading-indicator",
    "export": "LoadingIndicator",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu",
    "export": "Menu",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menubar",
    "export": "Menubar",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-group-list",
    "export": "MenuGroupList",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-screen",
    "export": "MenuScreen",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "menu-sheet",
    "export": "MenuSheet",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "action-sheet",
    "export": "ActionSheet",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "meter",
    "export": "Meter",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "milestone-trio",
    "export": "MilestoneTrio",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-bar",
    "export": "NavigationBar",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-bar-item",
    "export": "NavigationBarItem",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-drawer",
    "export": "NavigationDrawer",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-menu",
    "export": "NavigationMenu",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "navigation-rail",
    "export": "NavigationRail",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "number-field",
    "export": "NumberField",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "drawer",
    "export": "Drawer",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "popover",
    "export": "Popover",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "scroll-area",
    "export": "ScrollArea",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "pagination",
    "export": "Pagination",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "kern-pressable",
    "export": "KernPressable",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "progress",
    "export": "Progress",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "radio-group",
    "export": "RadioGroup",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "radio-group-item",
    "export": "RadioGroupItem",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "search",
    "export": "Search",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "select",
    "export": "Select",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "separator",
    "export": "Separator",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "shape-art",
    "export": "ShapeArt",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "shape",
    "export": "Shape",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet-surface",
    "export": "SheetSurface",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet",
    "export": "Sheet",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "sheet-handle",
    "export": "SheetHandle",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "bottom-sheet",
    "export": "BottomSheet",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snap-sheet",
    "export": "SnapSheet",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "dock-sheet",
    "export": "DockSheet",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "bottom-sheet-picker",
    "export": "BottomSheetPicker",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "entity-sheet",
    "export": "EntitySheet",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "boot-splash",
    "export": "BootSplash",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "error-boundary",
    "export": "ErrorBoundary",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "skeleton",
    "export": "Skeleton",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "slider",
    "export": "Slider",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "snackbar",
    "export": "Snackbar",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "split-button",
    "export": "SplitButton",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "split",
    "export": "Split",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "success-transform",
    "export": "SuccessTransform",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "switch",
    "export": "Switch",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "table",
    "export": "Table",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tabs",
    "export": "Tabs",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "text",
    "export": "Text",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "textarea",
    "export": "Textarea",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "time-picker",
    "export": "TimePicker",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toggle-group",
    "export": "ToggleGroup",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toggle",
    "export": "Toggle",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "toolbar",
    "export": "Toolbar",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "tooltip",
    "export": "Tooltip",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "top-app-bar",
    "export": "TopAppBar",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "top-app-bar-action",
    "export": "TopAppBarAction",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "command",
    "export": "Command",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "segmented-button",
    "export": "SegmentedButton",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "country-select",
    "export": "CountrySelect",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  },
  {
    "name": "banner",
    "export": "Banner",
    "platform": "native",
    "state": "Preview",
    "version": "0.0.0"
  }
] as const;

/** Export names grouped by state, for the site's filter chips. */
export const MATURITY_BY_STATE: Readonly<Record<MaturityState, readonly string[]>> = {
  "Preview": [
    "accordion",
    "accordion-header",
    "accordion-item",
    "accordion-panel",
    "accordion-root",
    "accordion-trigger",
    "action-sheet",
    "alert-dialog",
    "alert-dialog-close",
    "alert-dialog-content",
    "alert-dialog-description",
    "alert-dialog-root",
    "alert-dialog-title",
    "alert-dialog-trigger",
    "app-shell",
    "app-top-bar",
    "apps-menu",
    "aspect-ratio",
    "autocomplete",
    "autocomplete-content",
    "autocomplete-empty",
    "autocomplete-input",
    "autocomplete-item",
    "autocomplete-label",
    "autocomplete-root",
    "avatar",
    "avatar-fallback",
    "avatar-image",
    "avatar-root",
    "badge",
    "banner",
    "banner-action",
    "boot-indicator",
    "boot-splash",
    "bottom-sheet",
    "bottom-sheet-picker",
    "button",
    "button-group",
    "calendar",
    "card",
    "carousel",
    "checkbox",
    "checkbox-group",
    "checkbox-group-item",
    "checkbox-group-root",
    "chip",
    "circular-progress",
    "collapsible",
    "collapsible-panel",
    "collapsible-root",
    "collapsible-trigger",
    "combobox",
    "combobox-clear",
    "combobox-content",
    "combobox-empty",
    "combobox-input",
    "combobox-item",
    "combobox-label",
    "combobox-root",
    "combobox-trigger",
    "command",
    "command-content",
    "command-empty",
    "command-group-label",
    "command-input",
    "command-item",
    "command-list",
    "command-root",
    "command-separator",
    "context-menu",
    "context-menu-content",
    "context-menu-item",
    "context-menu-root",
    "context-menu-separator",
    "context-menu-trigger",
    "contrast-toggle",
    "country-select",
    "country-select-content",
    "country-select-item",
    "country-select-label",
    "country-select-root",
    "country-select-trigger",
    "country-select-value",
    "dialog",
    "dialog-close",
    "dialog-content",
    "dialog-description",
    "dialog-root",
    "dialog-title",
    "dialog-trigger",
    "dock-sheet",
    "document",
    "drawer",
    "drawer-close",
    "drawer-content",
    "drawer-description",
    "drawer-root",
    "drawer-title",
    "drawer-trigger",
    "empty-state",
    "entity-sheet",
    "error-boundary",
    "extended-fab",
    "fab",
    "fab-menu",
    "field",
    "field-description",
    "field-error",
    "field-label",
    "field-message",
    "field-root",
    "fieldset",
    "fieldset-item",
    "fieldset-legend",
    "fieldset-root",
    "filter-chip-row",
    "form",
    "help-menu",
    "icon-button",
    "icon-button-target",
    "input",
    "input-otp",
    "input-otp-input",
    "input-otp-root",
    "inspector",
    "kbd",
    "kern-error-boundary",
    "kern-pressable",
    "label",
    "linear-progress",
    "link",
    "link-provider",
    "list-detail",
    "list-item",
    "loader",
    "loading-button",
    "loading-indicator",
    "loading-region",
    "menu",
    "menu-content",
    "menu-group-label",
    "menu-group-list",
    "menu-item",
    "menu-root",
    "menu-screen",
    "menu-separator",
    "menu-sheet",
    "menu-trigger",
    "menubar",
    "menubar-content",
    "menubar-item",
    "menubar-menu",
    "menubar-root",
    "menubar-trigger",
    "meter",
    "meter-label",
    "meter-root",
    "meter-value",
    "milestone-trio",
    "native-select",
    "navigation-bar",
    "navigation-bar-item",
    "navigation-drawer",
    "navigation-menu",
    "navigation-menu-content",
    "navigation-menu-item",
    "navigation-menu-link",
    "navigation-menu-list",
    "navigation-menu-root",
    "navigation-menu-trigger",
    "navigation-rail",
    "navigation-rail-button",
    "notifications-menu",
    "number-field",
    "number-field-input",
    "number-field-root",
    "page",
    "page-loader",
    "pagination",
    "pane",
    "popover",
    "popover-close",
    "popover-content",
    "popover-description",
    "popover-root",
    "popover-title",
    "popover-trigger",
    "preview-card",
    "preview-card-content",
    "preview-card-root",
    "preview-card-trigger",
    "progress",
    "progress-label",
    "progress-root",
    "progress-value",
    "radio-group",
    "radio-group-item",
    "scroll-area",
    "scroll-area-root",
    "scroll-area-scrollbar",
    "scroll-area-viewport",
    "search",
    "search-bar",
    "secondary-tabs",
    "section-drawer",
    "segmented-button",
    "segmented-button-item",
    "segmented-button-root",
    "select",
    "select-content",
    "select-group-label",
    "select-item",
    "select-item-text",
    "select-root",
    "select-separator",
    "select-trigger",
    "select-value",
    "separator",
    "settings-row",
    "shape",
    "shape-art",
    "sheet",
    "sheet-close",
    "sheet-content",
    "sheet-description",
    "sheet-handle",
    "sheet-root",
    "sheet-surface",
    "sheet-title",
    "sheet-trigger",
    "sidebar",
    "sidebar-content",
    "sidebar-footer",
    "sidebar-header",
    "sidebar-item",
    "sidebar-provider",
    "skeleton",
    "slider",
    "slider-label",
    "slider-root",
    "slider-thumb",
    "slider-value",
    "snackbar",
    "snackbar-action",
    "snackbar-close",
    "snackbar-description",
    "snackbar-list",
    "snackbar-provider",
    "snackbar-root",
    "snackbar-title",
    "snackbar-viewport",
    "snap-sheet",
    "sonner",
    "sonner-action",
    "sonner-close",
    "sonner-description",
    "sonner-list",
    "sonner-provider",
    "sonner-root",
    "sonner-title",
    "sonner-viewport",
    "split",
    "split-button",
    "split-grid",
    "split-panel",
    "status-bar",
    "success-transform",
    "supporting-pane",
    "switch",
    "table",
    "table-body",
    "table-caption",
    "table-cell",
    "table-head",
    "table-header",
    "table-root",
    "table-row",
    "tabs",
    "tabs-list",
    "tabs-panel",
    "tabs-root",
    "tabs-tab",
    "text",
    "textarea",
    "theme-toggle",
    "time-picker",
    "toggle",
    "toggle-group",
    "toggle-group-item",
    "toggle-group-root",
    "toolbar",
    "toolbar-button",
    "toolbar-group",
    "toolbar-root",
    "toolbar-separator",
    "tooltip",
    "tooltip-content",
    "tooltip-provider",
    "tooltip-root",
    "tooltip-trigger",
    "top-app-bar",
    "top-app-bar-action",
    "top-app-bar-toggle",
    "top-bar-menu",
    "user-menu"
  ],
  "Stable": [],
  "Maintained": [],
  "Sunsetting": [],
  "Archived": []
} as const;

/**
 * Read one component's maturity. Returns undefined for a name the registry does
 * not know, so a stale content page renders nothing rather than claiming a state
 * for a component that does not exist.
 */
export function maturityFor(name: string): MaturityRow | undefined {
  return MATURITY.find((r) => r.name === name);
}
