// Generates tokens.css from tokens.json + theme presets.
// Run from the repo root: bun packages/kern-tokens/scripts/gen-css.mjs
// tokens.ts imports the canonical JSON directly; it is not a mirrored file.
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("../../..", import.meta.url).pathname;
const THEME = join(ROOT, "packages/kern-tokens/src");
const read = (file) => JSON.parse(readFileSync(join(THEME, file), "utf8"));
const kebab = (name) => name.replace(/(?<!^)(?=[A-Z])/g, "-").toLowerCase();
const roleVar = (role) => `--md-sys-color-${kebab(role)}`;

const T = read("tokens.json");
const M3 = read("themes/kern.json");
const sharp = read("themes/sharp.json");
const fontFamily = `"${T.typography.webFamily}", "${T.typography.family}", sans-serif`;
const prefix = (name) => `--md-sys-typescale-${name}`;
// Dark-mode shadows need higher opacity: black blurs are invisible on black
// surfaces, so each level steps its alphas up from the light definition.
const darkElevation = {
  level0: "none",
  level1: "0 1px 2px 0 rgba(0, 0, 0, 0.5), 0 1px 3px 1px rgba(0, 0, 0, 0.3)",
  level2: "0 1px 2px 0 rgba(0, 0, 0, 0.5), 0 2px 6px 2px rgba(0, 0, 0, 0.3)",
  level3: "0 1px 2px 0 rgba(0, 0, 0, 0.5), 0 4px 8px 3px rgba(0, 0, 0, 0.3)",
  level4: "0 2px 3px 0 rgba(0, 0, 0, 0.5), 0 6px 10px 4px rgba(0, 0, 0, 0.3)",
  level5: "0 4px 4px 0 rgba(0, 0, 0, 0.5), 0 8px 12px 6px rgba(0, 0, 0, 0.3)",
};
const sharpDarkColors = Object.entries(sharp.overrides.color?.dark ?? {});

const C = [
  '@import "@fontsource-variable/inter";',
  "",
  "/* Generated by scripts/gen-css.mjs from tokens.json and themes/. */",
  "/* OKLCH is canonical on web; tokens.json carries compiled sRGB for native. */",
  "",
  ":root {",
  ...Object.entries(M3.color.light).map(
    ([role, value]) => `  ${roleVar(role)}: ${value};`,
  ),
  "}",
  "",
  ".dark {",
  ...Object.entries(M3.color.dark).map(
    ([role, value]) => `  ${roleVar(role)}: ${value};`,
  ),
  "}",
  "",
  ".dark {",
  ...Object.entries(darkElevation).map(
    ([level, shadow]) => `  --md-sys-elevation-${level}: ${shadow};`,
  ),
  "}",
  "",
  ":root {",
  ...Object.entries(T.shape).map(
    ([name, value]) => `  --md-sys-shape-corner-${name}: ${value};`,
  ),
  // Skip DTCG metadata keys (`$comment`, `$schema`, …). They are annotations, not
  // tokens; emitting one produces an invalid custom-property name and a broken var.
  ...Object.entries(T.elevation)
    .filter(([level]) => !level.startsWith("$"))
    .flatMap(([level, value]) => [
      `  --md-sys-elevation-${level}: ${value.shadow};`,
      `  --md-sys-elevation-${level}-dp: ${value.dp};`,
    ]),
  ...Object.entries(T.typography.scale).flatMap(([name, style]) => [
    `  ${prefix(name)}-font-family: ${fontFamily};`,
    `  ${prefix(name)}-font-size: ${style.size};`,
    `  ${prefix(name)}-line-height: ${style.lineHeight};`,
    `  ${prefix(name)}-letter-spacing: ${style.tracking};`,
    `  ${prefix(name)}-font-weight: ${style.weight};`,
  ]),
  // Emphasized type scale (P1-3 / D-028): md.sys.typescale.emphasized.*.
  ...Object.entries(T.typography.scaleEmphasized ?? {}).flatMap(
    ([name, style]) => [
      `  ${prefix(`emphasized-${name}`)}-font-family: ${fontFamily};`,
      `  ${prefix(`emphasized-${name}`)}-font-size: ${style.size};`,
      `  ${prefix(`emphasized-${name}`)}-line-height: ${style.lineHeight};`,
      `  ${prefix(`emphasized-${name}`)}-letter-spacing: ${style.tracking};`,
      `  ${prefix(`emphasized-${name}`)}-font-weight: ${style.weight};`,
    ],
  ),
  // Motion (P1-4 / D-028). The three legacy keys stay verbatim at the top so existing
  // consumers keep resolving; the full grid is emitted alongside them.
  `  --md-sys-motion-easing-standard: ${T.motion["easing-standard"]};`,
  `  --md-sys-motion-duration-short: ${T.motion["duration-short"]};`,
  `  --md-sys-motion-duration-medium: ${T.motion["duration-medium"]};`,
  ...Object.entries(T.motion.easing ?? {})
    // `easing-standard` is already emitted by the legacy triple above and is the
    // same token (M3 names both). Emitting it twice trips Biome's
    // noDuplicateCustomProperties, so the pool skips it — the value still
    // resolves, and `schemes.standard.easing` points at it correctly.
    .filter(([name]) => name !== "standard")
    .map(([name, value]) => `  --md-sys-motion-easing-${name}: ${value};`),
  ...Object.entries(T.motion.duration ?? {}).map(
    ([name, value]) => `  --md-sys-motion-duration-${name}: ${value};`,
  ),
  ...Object.entries(T.motion.spring ?? {}).flatMap(([name, spring]) => [
    `  --md-sys-motion-spring-${name}-stiffness: ${spring.stiffness};`,
    `  --md-sys-motion-spring-${name}-damping: ${spring.damping};`,
  ]),
  ...Object.entries(T.motion.schemes ?? {}).flatMap(([scheme, refs]) =>
    Object.entries(refs).map(
      ([key, target]) =>
        `  --md-sys-motion-scheme-${scheme}-${key}: var(--md-sys-motion-${
          key.startsWith("easing") ? "easing" : "spring"
        }-${target});`,
    ),
  ),
  ...Object.entries(T.states).map(
    ([name, value]) =>
      `  --md-sys-state-${name.replace("-opacity", "")}: ${value};`,
  ),
  ...Object.entries(T.spacing).map(
    // M3 names spacing `space100 = 8dp` (P1-6). The key already carries the `space-`
    // prefix, so the var is `--md-sys-spacing-space-100`.
    ([step, value]) => `  --md-sys-spacing-${step}: ${value};`,
  ),
  ...Object.entries(T.spectrum).flatMap(([hue, ramp]) =>
    Object.entries(ramp).map(
      ([step, value]) => `  --spectrum-${hue}-${step}: ${value.srgb};`,
    ),
  ),
  `  --kern-font-family: ${fontFamily};`,
  "}",
  "",
  '[data-kern-theme="sharp"] {',
  ...Object.entries(sharp.overrides.color?.light ?? {}).map(
    ([role, value]) => `  ${roleVar(role)}: ${value};`,
  ),
  ...Object.entries(sharp.overrides.shape ?? {}).map(
    ([shape, value]) => `  --md-sys-shape-corner-${shape}: ${value};`,
  ),
  "}",
  "",
  ...(sharpDarkColors.length > 0
    ? [
        '.dark[data-kern-theme="sharp"] {',
        ...sharpDarkColors.map(
          ([role, value]) => `  ${roleVar(role)}: ${value};`,
        ),
        "}",
        "",
      ]
    : []),
  "/* App-token bridge for consumers using generic semantic names. */",
  ":root {",
  "  --background: var(--md-sys-color-surface);",
  "  --foreground: var(--md-sys-color-on-surface);",
  "  --card: var(--md-sys-color-surface);",
  "  --primary: var(--md-sys-color-primary);",
  "  --primary-foreground: var(--md-sys-color-on-primary);",
  "  --secondary: var(--md-sys-color-surface-container-high);",
  "  --muted: var(--md-sys-color-surface-container-high);",
  "  --accent: var(--md-sys-color-surface-tonal);",
  "  --muted-foreground: var(--md-sys-color-on-surface-variant);",
  "  --border: var(--md-sys-color-outline-variant);",
  "  --destructive: var(--md-sys-color-error);",
  "  --radius: var(--md-sys-shape-corner-small);",
  "  --sidebar: var(--md-sys-color-surface);",
  "  --sidebar-foreground: var(--md-sys-color-on-surface);",
  "  --sidebar-primary: var(--md-sys-color-primary);",
  "  --sidebar-primary-foreground: var(--md-sys-color-on-primary);",
  "  --sidebar-accent: var(--md-sys-color-surface-container-high);",
  "  --sidebar-accent-foreground: var(--md-sys-color-on-surface);",
  "  --sidebar-border: var(--md-sys-color-outline-variant);",
  "}",
  "",
  "@theme inline {",
  ...Object.keys(M3.color.light).map(
    (role) => `  --color-${kebab(role)}: var(${roleVar(role)});`,
  ),
  ...Object.entries(T.shape).map(
    ([name]) =>
      `  --radius-${kebab(name)}: var(--md-sys-shape-corner-${name});`,
  ),
  ...Object.entries(T.spectrum).flatMap(([hue, ramp]) =>
    Object.entries(ramp).map(
      ([step]) =>
        `  --color-spectrum-${hue}-${step}: var(--spectrum-${hue}-${step});`,
    ),
  ),
  ...Object.entries(T.typography.scale).map(
    ([name, style]) =>
      `  --text-${name}: ${style.size};\n  --text-${name}--line-height: ${style.lineHeight};\n  --text-${name}--letter-spacing: ${style.tracking};\n  --text-${name}--font-weight: ${style.weight};`,
  ),
  "  --font-sans: var(--kern-font-family);",
  ...Object.entries(T.spacing).map(
    ([step, value]) => `  --spacing-${step}: ${value};`,
  ),
  "  --color-background: var(--background);",
  "  --color-foreground: var(--foreground);",
  "  --color-card: var(--card);",
  "  --color-primary: var(--primary);",
  "  --color-primary-foreground: var(--primary-foreground);",
  "  --color-secondary: var(--secondary);",
  "  --color-muted: var(--muted);",
  "  --color-accent: var(--accent);",
  "  --color-muted-foreground: var(--muted-foreground);",
  "  --color-border: var(--border);",
  "  --color-destructive: var(--destructive);",
  "}",
];

writeFileSync(join(THEME, "tokens.css"), `${C.join("\n")}\n`);
// Emit Biome-canonical formatting so `bun run lint` stays clean on regen.
const out = join(THEME, "tokens.css");
const fmt = spawnSync(
  "bun",
  ["x", "@biomejs/biome", "format", "--write", out],
  { cwd: ROOT, stdio: "inherit" },
);
if (fmt.status !== 0) process.exit(fmt.status ?? 1);
console.log("tokens.css regenerated");
