// Generates src/theme/tokens.css from tokens.json + themes/m3.json.
// Run from the repo root: bun packages/kern/scripts/gen-css.mjs
// Role vars are kebab-case per M3 (--md-sys-color-on-surface).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("../../..", import.meta.url).pathname;
const THEME = join(ROOT, "packages/kern/src/theme");

const kebab = (name) => name.replace(/(?<!^)(?=[A-Z])/g, "-").toLowerCase();
const roleVar = (role) => `--md-sys-color-${kebab(role)}`;

const T = JSON.parse(readFileSync(join(THEME, "tokens.json"), "utf8"));
const M = JSON.parse(readFileSync(join(THEME, "themes/m3.json"), "utf8"));

const C = [
  "/* Kern theme CSS — generated by scripts/gen-css.mjs from",
  " * tokens.json + themes/m3.json. Roles bind palette steps per M3 rules.",
  " * Native consumes compiled srgb hex instead (see tokens.json).",
  " * Do not hand-edit values. */",
  "",
  ":root {",
  ...Object.entries(M.color.light).map(
    ([role, value]) => `  ${roleVar(role)}: ${value};`,
  ),
  "}",
  "",
  ".dark {",
  ...Object.entries(M.color.dark).map(
    ([role, value]) => `  ${roleVar(role)}: ${value};`,
  ),
  "}",
  "",
  "/* Shape, elevation, motion, state layers (mode-independent). */",
  ":root {",
  ...Object.entries(T.shape).map(
    ([name, value]) => `  --md-sys-shape-corner-${name}: ${value};`,
  ),
  ...Object.entries(T.elevation).map(
    ([level, value]) => `  --md-sys-elevation-${level}: ${value};`,
  ),
  `  --md-sys-motion-easing-standard: ${T.motion["easing-standard"]};`,
  `  --md-sys-motion-duration-short: ${T.motion["duration-short"]};`,
  `  --md-sys-motion-duration-medium: ${T.motion["duration-medium"]};`,
  ...Object.entries(T.states).map(
    ([name, value]) =>
      `  --md-sys-state-${name.replace("-opacity", "")}: ${value};`,
  ),
  "}",
  "",
  "/* Tailwind v4 named utilities (member roles). Requires Tailwind v4. */",
  "@theme inline {",
  ...[
    "primary",
    "onPrimary",
    "secondary",
    "onSecondary",
    "surface",
    "onSurface",
    "surfaceTonal",
    "error",
    "onError",
    "surfaceContainer",
    "outline",
    "outlineVariant",
  ].map((role) => `  --color-${kebab(role)}: var(${roleVar(role)});`),
  "}",
];

writeFileSync(join(THEME, "tokens.css"), `${C.join("\n")}\n`);
console.log("tokens.css regenerated");
